spring:
  jpa:
    open-in-view: false
    database: POSTGRESQL
    show-sql: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.jdbc.lob.non_contextual_creation: true
    hibernate:
      ddl-auto: none
  datasource:
    name: RPGI
    username: rpgi-user
    password: rpgi-user
    url: jdbc:postgresql://localhost:5432/rpgi
  liquibase:
    change-log: classpath:db/liquibase-main.xml
  jackson:
    serialization.write_dates_as_timestamps: false

  resources:
    static-locations:
      - classpath:/app-dist/
  security:
    oauth2:
      client:
        registration:
          rpgi:
            client-id: ${application.keycloak-client.client-id}
            client-secret: ${application.keycloak-client.secret}
            client-name: rpgi-web
            provider: keycloak
            scope: openid, profile
            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            token-uri: ${application.keycloak-client.uri}/realms/${application.keycloak-client.realm}/protocol/openid-connect/token
            authorization-uri: ${application.keycloak-client.uri}/realms/${application.keycloak-client.realm}/protocol/openid-connect/auth
            user-info-uri: ${application.keycloak-client.uri}/realms/${application.keycloak-client.realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${application.keycloak-client.uri}/realms/${application.keycloak-client.realm}/protocol/openid-connect/certs
            user-name-attribute: preferred_username
  application:
    name: RPG Inventory - WEB
    admin:
      enabled: false

application:
  keycloak-client:
    uri: http://localhost:8180/auth
    realm: rpgi
    secret: 2630ec46-05e9-4803-9010-727b9d08d57b
    client-id: rpgi-web
    ssl-required: none
    confidential-port: 0
